version: 2
registries:
  jfrog-artifactory:
    type: npm-registry
    url: "https://entur2.jfrog.io/entur2"
    token: ${{secrets.ARTIFACTORY_AUTH_TOKEN}}
updates:
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
        - "minor"
        - "patch"
  - package-ecosystem: "npm"
    directory: "/fixture/functions"
    registries:
      - jfrog-artifactory
    groups:
      minor-and-patch:
        applies-to: version-updates
        update-types:
        - "minor"
        - "patch"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 2

