version: 2
registries:
  jfrog-artifactory:
    type: npm-registry
    url: "https://entur2.jfrog.io/entur2"
    token: ${{secrets.ARTIFACTORY_AUTH_TOKEN}}
updates:
- package-ecosystem: github-actions
  directory: "/"
  groups:
    minor-and-patch:
      applies-to: version-updates
      update-types:
        - "minor"
        - "patch"
  schedule:
    interval: "weekly"
    time: "09:00"
    timezone: "Europe/Oslo"
    day: "monday"
  commit-message:
    prefix: "fix"  # Use 'fix' for GitHub Actions updates so we get new releases
    prefix-development: "chore" # Use 'chore' for development dependency updates
    include: "scope"
  open-pull-requests-limit: 2
- package-ecosystem: "npm"
  directory: "/fixture/functions"
  registries:
    - jfrog-artifactory
  groups:
    minor-and-patch:
      applies-to: version-updates
      update-types:
      - "minor"
      - "patch"
  schedule:
    interval: "weekly"
    time: "09:00"
    timezone: "Europe/Oslo"
    day: "monday"
  open-pull-requests-limit: 2
  commit-message:
    prefix: "chore" # Use 'chore' for testing and build tool updates
    prefix-development: "chore" # Use 'chore' for development dependency updates
    include: "scope"
