name: PR
on:
  pull_request:

jobs:
  verify-pr:
    name: Verify PR
    if: ${{ github.event_name == 'pull_request' }}
    uses: entur/gha-meta/.github/workflows/verify-pr.yml@v1
  firebase-preview-dev:
    name: Firebase Hosting Preview
    uses: ./.github/workflows/firebase-hosting-preview.yml
    with:
      gcp_project_id: ent-ghafb-dev
      environment: dev
      entry_point: fixture
      preview_expire: 1d
  tests:
    name: Run tests
    needs: firebase-preview-dev
    runs-on: ubuntu-24.04
    env:
      PREVIEW_URL: ${{ needs.firebase-preview-dev.outputs.details_url }}
    steps:
      - name: Run tests
        run: |
          curl --fail --silent --show-error --connect-timeout 10 -I ${PREVIEW_URL}
  firebase-deploy-dev:
    name: Firebase Hosting Deploy
    needs: tests
    uses: ./.github/workflows/firebase-hosting-deploy.yml
    with:
      gcp_project_id: ent-ghafb-dev
      environment: dev
      entry_point: fixture
  # Commented out due to bug in https://github.com/FirebaseExtended/action-hosting-deploy/issues/388
  # post-deploy-tests:
  #   name: Run tests after deploy
  #   runs-on: ubuntu-latest
  #   needs: firebase-deploy-dev
  #   env:
  #     TEST_URL: ${{ needs.firebase-deploy-dev.outputs.details_url }}
  #   steps:
  #     - name: Run tests
  #       run: |
  #         curl --fail --silent --show-error --connect-timeout 10 -I ${TEST_URL}
  # TODO Test artifact up/download ?

  update-firebase-hosting-deploy-doc:
    name: Update Firebase Hosting Deploy Doc
    needs: [firebase-deploy-dev]
    uses: entur/gha-meta/.github/workflows/auto-doc.yml@v1
    with:
      workflow_file: .github/workflows/firebase-hosting-deploy.yml
      readme_file: README-firebase-hosting-deploy.md

  update-firebase-hosting-preview-doc:
    name: Update Firebase Hosting Preview Doc
    needs: [firebase-deploy-dev]
    uses: entur/gha-meta/.github/workflows/auto-doc.yml@v1
    with:
      workflow_file: .github/workflows/firebase-hosting-preview.yml
      readme_file: README-firebase-hosting-preview.md
