name: PR
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  checks: write
  contents: read
  pull-requests: write
  id-token: write
  issues: write

jobs:
  firebase-preview-dev:
    uses: ./.github/workflows/firebase-hosting-preview.yml
    with:
      gcp_project_id: ent-ghafb-dev
      environment: dev
      entryPoint: fixture
      preview_expire: 1d
  tests:
    runs-on: ubuntu-latest
    needs: firebase-preview-dev
    env:
      PREVIEW_URL: ${{ needs.firebase-preview-dev.outputs.preview_url }}
    steps:
      - name: Run tests
        run: |
          curl --silent --show-error --connect-timeout 10 -I ${PREVIEW_URL}|grep 200  && echo "Success" || echo "Failed" && exit 1
