name: Entur/Firebase/Preview

# used for creating firebase previews for use in ie: PRs

on:
  workflow_call:
    inputs:
      gcp_project_id:
        required: true
        type: string
        description: "GCP Project ID"
      environment:
        required: true
        type: string
        description: "Environment to deploy to (dev, tst, prd)"
      entryPoint:
        type: string
        description: "Entry point folder to deploy"
        default: "."
      build_artifact_name:
        description: "Name of GitHub artifact to add to build"
        type: string
      build_artifact_path:
        description: "Path to the artifact"
        type: string
        default: "build"
      preview_expire:
        type: string
        description: "Preview expire time"
        default: "7d"
      timeout_minutes:
        description: "Timeout in minutes"
        type: number
        default: 20

jobs:
  deploy_preview:
    permissions:
      checks: write
      contents: read
      pull-requests: write
      id-token: write
    runs-on: ubuntu-latest
    timeout-minutes: ${{ inputs.timeout_minutes }}
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: auth
        uses: "google-github-actions/auth@v2"
        with:
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT }}
          create_credentials_file: true

      - run: |
          echo "SERVICE_ACCOUNT_KEY=$(cat "${{ steps.auth.outputs.credentials_file_path }}" | tr -d '\n')" >> $GITHUB_ENV

      - id: download-artifact
        uses: actions/download-artifact@v4
        if: inputs.build_artifact_name != ''
        with:
          name: ${{ inputs.build_artifact_name }}
          path: ${{ inputs.build_artifact_path }}

      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          firebaseServiceAccount: "${{ env.SERVICE_ACCOUNT_KEY }}"
          projectId: ${{ inputs.gcp_project_id }}
          entryPoint: ${{ inputs.entryPoint }}
          expires: ${{ inputs.preview_expire }}

      - name: Add comment with preview url
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: pullRequest } = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number
            });
            const previewUrl = `https://${process.env.GITHUB_HEAD_REF}-${process.env.GITHUB_SHA.slice(0, 7)}-${process.env.GITHUB_RUN_NUMBER}-${process.env.GITHUB_RUN_ID}.web.app`;
            const comment = `Preview available at ${previewUrl}`;
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: pullRequest.number,
              body: comment
            });
